### ISSUE TITLE
OpenAPI document doesn't take into account multiple applications deployment

### ISSUE THREAD

**Issue by peterpz1** [eclipse/microprofile#168] opened 2020-02-25 08:24 UTC
It would be a lot better to have openapi document per application, not single document per server, because it causes no possibility to use it when you have >1 application on server.

**Comment by kenfinnigan** [comment] 2020-02-25 08:29
MicroProfile is designed around microservices, which aligns with single application per server.

What would be the use case for MicroProfile supporting multiple applications on a single server?

**Comment by peterpz1** [comment] 2020-02-25 09:03
So I don't know why our application server (Payara) in Full mode (not microprofile) is supporting this feature. In Full mode multiple applications are normal case, and since they implemented this feature in this mode it doesn't align properly with the assumption of single application.

**Comment by kenfinnigan** [comment] 2020-02-25 09:14
So you agree it's an issue with Payara Full and not MicroProfile?

**Comment by peterpz1** [comment] 2020-02-25 09:38
Payara sent me here :) https://github.com/payara/Payara/issues/4470#issuecomment-590726272

**Comment by phillip-kruger** [comment] 2020-02-25 09:39
I guess Wildfly and OpenLiberty will have the same issue.

**Comment by kenfinnigan** [comment] 2020-02-25 09:40
@peterpz1 I'd consider this a Payara Full issue, and I don't see MicroProfile breaking away from the goal of microservices and single application/deployments

**Comment by rdebusscher** [comment] 2020-02-25 09:46
I'm not sure this is a Payara issue only. We do, just as other runtimes,
support MicroProfile specs in combination with the Jakarta specs. But the
behavior of MicroProfile is not specified in the case when there are
multiple applications deployed. So There is no behavior specified in case
you use it that way.

Now that MicroProfile will go his own way, the intended behavior will need
to be defined in the upcoming Jakarta OpenAPI Spec.

**Comment by kenfinnigan** [comment] 2020-02-25 09:54
MicroProfile, as a whole, is based around the notion of microservices, and as such is aligned with a single deployment/application.

I believe "multiple" applications are explicitly not defined in specifications to allow implementations to handle this situation, if they so choose, without being precluded from doing so by the specification.

What upcoming Jakarta OpenAPI spec are you referring to?

**Comment by rdebusscher** [comment] 2020-02-25 10:03
The fork of MP OpenAPI into Jakarta as discussed in the MP Hangout meetings
about the technical alignment.

Jakarta will require some changes to the MP specs like for example the
multiple application support. So it will be a fork of the code with
adjustments to code and spec to accommodate Jakarta specifics.

**Comment by kenfinnigan** [comment] 2020-02-25 10:09
There is no fork at present.

My understanding was that the technical alignment discussion leads to Jakarta doing what it wants with MP specs. That doesn't automatically lead to Jakarta wanting OpenAPI, or am I missing something?

**Comment by rdebusscher** [comment] 2020-02-25 10:19
>There is no fork at present.

That is why I said 'upcoming'

>That doesn't automatically lead to Jakarta wanting OpenAPI, or am I
missing something?

Since MP specs are very popular in combination with Java EE/Jakarta EE that
is a logical next step

MP config -> Jakarta config
MP OpenAPI -> Jakarta OpenAPI
MP Metrics -> Jakarta Metrics
MP Rest Client -> Inclusion in Jakarta REST
MP JWT Auth -> Inclusion in Jakarta Security API
MP Health -> Jakarta Health
...

**Comment by kenfinnigan** [comment] 2020-02-25 10:23
Ok, just wanted to make sure I understood what you meant

**Comment by rhuan080** [comment] 2020-07-05 22:10
Hi,
Wildfly has the same issue. Many of the MP specs are very interesting to the Jakarta EE apps and I think it is good to be possible use it without fork the specs. In fact, the microservice is aligned with a single application per server, but I think the MP spec don't need to define it and keep it open to the implementation. It has any problem in keeping it open to the implementation?

**Comment by Blubb324** [comment] 2020-07-14 07:29
Hey, I also think that the support for multiple applications at one server is extremly useful. I know that the best behaviour for microservices is one artefact per server. But, image if there are really two little rest-apps - is it really necessary to build a complete microservice-architecture with docker/kubernetes and several servers (which are also using resources)? Another case is that sometimes you are limited by the clients (not every company is big enough to handle microservices) and they are just deploying several apps into one server.

Additionally it would be great if it wouldn´t be necessary to fork the specs - we all know the benefits of standards. :) On the other hand I can´t participate in this decision because I´m not close to the developement and I don´t know the code and what´s technical possible.

Thanks for your great work guys!

**Comment by bfedoronchuk** [comment] 2021-07-20 14:56
It will be useful to support multiple OpenAPI files and endpoints for multiple API versions. For example:
openapi-v1.yaml file -> /openapi-v1 endpoint
openapi-v2.yaml file -> /openapi-v2 endpoint

**Comment by peterpz1** [comment] 2022-02-23 08:17
We are still in the same place 2 years later? Are there any decisions on the issue? On "full" type of servers when in the a lot of cases there are >1 apps there should be some solution for that...

**Comment by Emily-Jiang** [comment] 2022-02-27 22:23
The spec has [this](https://download.eclipse.org/microprofile/microprofile-open-api-2.0.1/microprofile-openapi-spec-2.0.1.html#_multiple_applications) clarification on multiple applications per server. I know Open Liberty has the support for multiple applications per server api doc generation.

**Comment by Emily-Jiang** [comment] 2024-10-29 21:17
close as this is out of scope for the spec. Implementations can choose to support it.

**Closed by Emily-Jiang** 2024-10-29 21:17 UTC
Labels: Architecture board
